config/routes.rb
Rails.application.routes.draw do
  root to:'the_gossip_project#welcome'
  get '/team', to: 'the_gossip_project#team'
  get '/contact', to: 'the_gossip_project#contact'
  get '/welcome/:potineur', to: 'the_gossip_project#welcome'
  get '/welcome', to: 'the_gossip_project#welcome'
  resources :gossips
  resources :users
  resources :tags
  resources :cities


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
 has_many :tag_and_gossips
 has_many :tags, through: :tag_and_gossips
 validates :title, presence: true, length: { in: 3..14 }
 validates :content, presence: true
 belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User", optional: true
  belongs_to :recipient, class_name: "User", optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
 has_many :tag_and_gossips
 has_many :gossips, through: :tag_and_gossips
end

app/models/tag_and_gossip.rb
class TagAndGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
  
    # if user is logged in, return current_user, else return guest_user
    def current_or_guest_user
      if current_user
        if session[:guest_user_id] && session[:guest_user_id] != current_user.id
          logging_in
          # reload guest_user to prevent caching problems before destruction
          guest_user(with_retry = false).try(:reload).try(:destroy)
          session[:guest_user_id] = nil
        end
        current_user
      else
        guest_user
      end
    end
  
    # find guest_user object associated with the current session,
    # creating one as needed
    def guest_user(with_retry = true)
      # Cache the value the first time it's gotten.
      @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
  
    rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
       session[:guest_user_id] = nil
       guest_user if with_retry
    end
  
    private
  
    # called (once) when the user logs in, insert any code your application needs
    # to hand off from guest_user to current_user.
    def logging_in
      # For example:
      # guest_comments = guest_user.comments.all
      # guest_comments.each do |comment|
        # comment.user_id = current_user.id
        # comment.save!
      # end
    end
  
    def create_guest_user
      u = User.new(first_name: "Anonymous",last_name:"Name", email: "guest_#{Time.now.to_i}#{rand(100)}@example.com")
      u.save!(validate: false)
      session[:guest_user_id] = u.id
      u
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    @city.update(city_params)
    redirect_to cities_path
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to cities_path
  end

  def new
    @city = City.new
  end

  def create
    @city = City.create(city_params)
    redirect_to cities_path
  end

  def edit
    @city = User.find(params[:id])
  end

  private

  def city_params
    params.require(:city).permit(:zip_code, :name)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips = Gossip.all
  end

  def show
    @gossips = Gossip.find(params[:id])
  end

  def new
    @gossips = Gossip.new
  end

  def create
    @gossips = Gossip.create(post_params)

    if @gossips.save
      redirect_to gossips_path
    else
      puts "try again"
      render :new
    end
  end

  def edit
    @gossips = Gossip.find(params[:id])
  end

  def update
    @gossips = Gossip.find(params[:id])
    if @gossips.update(post_params)
      redirect_to gossips_path
    else
      render :edit
    end
  end

  def destroy
    @gossips = Gossip.find(params[:id])
    @gossips.destroy
    redirect_to gossips_path
  end

  private
  def post_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update(tag_params)
    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    redirect_to tags_path
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end
end

app/controllers/the_gossip_project_controller.rb
class TheGossipProjectController < ApplicationController
  def team 
  end

  def contact 
  end

  def welcome
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def new
    @user = User.new
  end

def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:firt_name, :last_name, :email, :age, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/the_gossip_project_helper.rb
module TheGossipProjectHelper
end

app/views/cities/show.html.erb
<body>
  <h1 class="d-flex justify-content-center"><%=@city.name%>, bonjour !</h1><br>
  <p>Voici la liste des potins de <%=@city.name%>...</p>

  <%Gossip.all.each do |gossip|%>
  <button type="button" class="list-group-item list-group-item-action">
    <p class="text-capitalize">Titre : <%=gossip.title%></p>
    <p>Gossip : <%=gossip.content%><br></p>

  </button>
  <%end%>

</body>

app/views/gossips/edit.html.erb
<body>

  <h1 class="d-flex justify-content-center">Editer le Gossip n°<%= params[:id]%> !</h1><br>
<%= form_for @gossips do |f| %>
<div class="form-group">
  <label>Titre</label>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <label>Contenu</label>
  <%= f.text_area :content, class: 'form-control' %>
</div>
<div class="form-group">
  <button type="submit" class='btn btn-primary'>Modifier</button>
</div>
<% end %>
</body>
</html>

app/views/gossips/index.html.erb
<body>
  <div class="jumbotron">
    <div class="container">
      <p>Je te présente LE bouton qui te permettra de créer un potin...</p>
      <p><a href="<%= new_gossip_path%>" class="btn btn-success" href="#" role="button">Créer un nouveau potin</a></p>
    </div>
  </div>
  <tbody>
  </tbody>

  <div class="row">
    <%@gossips.each do |gossip|%>
    <div class="col-md-4">
      <h3><%= gossip.title %></h3>
      <p><a href="<%= gossip_path(gossip.id)%>"> <%=gossip.user.first_name %> qui habite à</a><br>
        <a href="cities/<%=(gossip.user.city.id)%>"><%=gossip.user.city.name%></a></p>
        <p><a href="<%= edit_gossip_path(gossip.id)%>" class="btn btn-primary" role="button">Editer</a><a href="<%= gossip_path(gossip.id)%>" class="btn btn-danger" role="button" data-confirm="Etes vous-sûr ?" data-method="DELETE">Supprimer</a></p>
      </div>
      <% end %>
    </div>

    <hr>
  </body>

app/views/gossips/new.html.erb
<body>

<h1 class="d-flex justify-content-center">Créer un Gossip</h1><br>

<%= form_tag url_for(action: 'create'), method: "post" do %>

<%= label_tag 'Title' %>
<%= text_field_tag 'title', @gossips.title %>
<br /> <br />

<%= label_tag 'Content' %>
<%= text_area_tag 'content', @gossips.content %>
<br /> <br />

<%= submit_tag "Create Gossip" %>

<% if @gossips.errors.any? %>
<p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
<ul>
  <% @gossips.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<% end %>

</form>
</body>
</html>


<!-- >

app/views/gossips/show.html.erb
<body>
<h1 class="d-flex justify-content-center">Voici la page du Gossip n°<%= params[:id]%> !</h1><br>
<div class="row justify-content-center">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @gossips.title%></h5>
    <h3 class="card-title"></h3>
    <p class="card-text"><%= @gossips.content%> </p>
    <a href="/users/<%=@gossips.user.id%>" class="btn btn-primary d-flex justify-content-center"><%=@gossips.user.first_name%> <%=@gossips.user.last_name%></a>
    <p><br>🏠<a href="/cities/<%=@gossips.user.city.id%>"><%=@gossips.user.city.name%></a></p>
   </div>
    </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TheGossipProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <%= javascript_include_tag 'application' %>
  
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/gossips">Gossips<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/team">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container" style="padding-top: 5rem;">

  <%= yield %>
</body>
</html>

app/views/tags/edit.html.erb
<body>
  
  <h1>Modifier le Tag</h1>

<%= form_for @tag do |t| %>
<div class="form-group">
<%= t.text_field :title, placeholder: 'Nom', class: 'form-control' %>
</div>
<div class="form-group">
  <button class="btn btn-primary" type="submit">Modifier le tag</button>
</div>
<% end %>
</body>
</html>

app/views/tags/index.html.erb
<body>
  
<h1>Les tags</h1>

<table class="table">
  <thead>
    <tr>
      <td>ID</td>
      <td>Nom du tag</td>
      <td>Actions</td>
    </tr>
  </thead>

  <tbody>
    <% Tag.all.each do |t| %>
    <tr>
      <td> <%= t.id %></td>
      <td> <%= t.title %></td>
      <td>
        <a href="<%= edit_tag_path(t.id)%>" class="btn btn-primary">Editer</a>
        <a href="<%= tag_path(t.id)%>" class="btn btn-danger" data-confirm="Etes-vous sûr de supprimer cette catégorie ?" data-method="DELETE">Supprimer</a>
    </tr>

    <% end %>

  </tbody>

</table>

<p>

          <a href="<%= new_tag_path%>" class="btn btn-success">Créer une nouvelle catégorie</a>

</p>

</body>
</html>


<!-- >

app/views/tags/new.html.erb
<body>

<h1>Créer un Tag</h1>

<%= form_for @tag do |t| %>
<div class="form-group">
<%= t.text_field :title, placeholder: 'Nom', class: 'form-control' %>
</div>
<div class="form-group">
  <button class="btn btn-primary" type="submit">Créer un tag</button>
</div>
<% end %>
</body>
</html>


<!-- >

app/views/the_gossip_project/contact.html.erb
<body>

<section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Nous contacter</h2>
            </div>
            <form id="contactForm" name="sentMessage" novalidate="novalidate">
                <div class="row align-items-stretch mb-5">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input class="form-control" id="name" type="text" placeholder="Prénom *"
                                required="obligatoire"
                                data-validation-required-message="Merci d'entrer votre prénom." />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="email" type="email" placeholder="Nom *"
                                required="obligatoire" data-validation-required-message="Merci d'entrer votre nom." />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group mb-md-0">
                            <input class="form-control" id="phone" type="tel" placeholder="Adresse mail *"
                                required="obligatoire"
                                data-validation-required-message="Merci d'entrer votre adresse mail." />
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-textarea mb-md-0">
                            <textarea class="form-control" id="message"
                                placeholder="Une suggestion ? Un message de d'encouragement ? :)"></textarea>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <div id="success"></div>
                    <button class="btn btn-primary btn-xl text-uppercase" id="sendMessageButton"
                        type="submit">Envoyer</button>
                </div>
            </form>
        </div>
    </section>

</body>
</html>

app/views/the_gossip_project/team.html.erb
<body>
  <h1 class="text-center p-3">L'équipe</h1>

  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="team-member">
        <img class="mx-auto rounded-circle" src="jb.jpg" alt="" />
        <h4>Nicolas Pelletier</h4>
        <p class="text-muted mt-2 mb-2">Relation client</p>
        <p class="card-text">
          " Le corse "
        </p>
        <p class="card-title">
          Le moteur
        </p>
      </div>
    </div>

    <div class="col-md-8 offset-md-2">
      <div class="team-member">
        <img class="mx-auto rounded-circle" src="sid.png" alt="" />
        <h4>Sidney Audibert</h4>
        <p class="text-muted mt-2 mb-2">Commercial</p>
        <p class="card-text">
          " Le sudiste "
        </p>
        <p class="card-title">Le roi de la boucle</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="team-member">
        <img class="mx-auto rounded-circle" src="felicie.jpg" alt="" />
        <h4>Félicie Bernard</h4>
        <p class="text-muted mt-2 mb-2">Ingénieur son</p>
        <p class="card-text">
          " La normande "
        </p>
        <p class="card-title">
          La fanfaronne
        </p>
      </div>
    </div>
    <div class="col-md-8 offset-md-2">
      <div class="team-member">
        <img class="mx-auto rounded-circle" src="loick.jpg" alt="" />
        <h4>Loïck Jouan</h4>
        <p class="text-muted mt-2 mb-2">Testeur d'ambiance</p>
        <p class="card-text">
          " Le nantais "
        </p>
        <p class="card-title">
          Le raleur motivé
        </p>
      </div>
    </div>
  </div>
</body>

app/views/the_gossip_project/welcome.html.erb
<body>
  <h1 class="text-center p-3"> 
    Salut à toi <%= params[:potineur]%> !<br> <br>
  Bienvenue dans le monde du gossip ! <br> Découvre les derniers potins tous frais, crée, supprime à ta guise 😽</h1>
  <h2 class="text-center p-3"><a href="<%= gossips_path %>"> Accéder aux gossips</a></h2>
</body>

app/views/users/show.html.erb
<body>
<h1 class="text-center p-3"> Salut à toi potineur n°<%= params[:id]%> !</h1>

<h1 class="text-center p-3"> Voici tes informations personnelles ultra secrètes </h1>




<pre>
Prénom : <%= @user.first_name %>
Nom : <%= @user.last_name %>
Description : <%= @user.description %>
E-mail : <%= @user.email %>
Age : <%= @user.age %>
City : <a href=cities_path><%= @user.city.name %></a>
</pre>

</body>

</html>